Models/ErrorViewModel.cs
namespace TEST_TPLUS.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/GraphViewModel.cs
namespace TEST_TPLUS.Models
{
    public class GraphViewModel
    {
           
    }
}

Models/HouseViewModel.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TEST_TPLUS.Domain.Entities;

namespace TEST_TPLUS.Models
{
    public class HouseViewModel
    {
        public HouseViewModel() { }
        public string? Name { get; set; }


    }
}

Controllers/GraphController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Newtonsoft.Json;
using TEST_TPLUS.Domains;

namespace TEST_TPLUS.Controllers
{
    public class GraphController : Controller
    {
        private readonly DataManager dataManager;

        private readonly AppDbContext context;

        public GraphController(DataManager dataManager, AppDbContext context)
        {
            this.dataManager = dataManager;
            this.context = context;
        }

        public record Houses(string Name, List<double> Consumption);
        public record Plants(string Name, List<double> Consumption);

        [HttpGet]
        public ActionResult GetHouses()
        {
            var response = dataManager.Houses.GetIncludeHouse();

            // Выводим Дома, Сгруппированная Погода, Суммированное Потребление
            var query = from house in context.Houses
                        join cons in context.HouseConsumptions on house.ConsumerId equals cons.HouseConsumerId into houseCons
                        from hcons in houseCons.DefaultIfEmpty()
                        group hcons by new { house.Name, hcons.Weather } into g
                        select new
                        {
                            g.Key.Name,
                            Weather = g.Key.Weather,
                            Consumption = g.Sum(x => x.Consumption)
                        };

            List<Houses> houses = new List<Houses>();

            var resp = query.ToList();

            foreach (var item in response)
            {
                houses.Add(new Houses
                (
                    item.Name,
                    resp.Where(x => x.Name == item.Name).Select(x => x.Consumption).ToList()
                )
                ); 
            }            

            return View("HouseView", houses);
        }

        [HttpGet("api/weather")]
        public ActionResult GetWeather()
        {

            var result = context.HouseConsumptions.Select(c => c.Weather).Distinct().OrderBy(w => w);

            if (result is null)
            {
                return NotFound();
            }

            string json = JsonConvert.SerializeObject(result);
            return Ok(json);
        }


        [HttpGet]
        public ActionResult GetPlants()
        {
            var response = dataManager.Plants.GetIncludePlant();

            // Выводим Дома, Сгруппированная Погода, Суммированное Потребление
            var query = from plant in context.Plants
                        join cons in context.PlantConsumptions on plant.ConsumerId equals cons.PlantConsumerId into plantCons
                        from pcons in plantCons.DefaultIfEmpty()
                        group pcons by new { plant.Name, pcons.Price } into g
                        select new
                        {
                            g.Key.Name,
                            Price = g.Key.Price,
                            Consumption = g.Sum(x => x.Consumption)
                        };

            List<Plants> plants = new List<Plants>();

            var resp = query.ToList();

            foreach (var item in response)
            {
                plants.Add(new Plants
                (
                    item.Name,
                    resp.Where(x => x.Name == item.Name).Select(x => x.Consumption).ToList()
                )
                );
            }

            return View("PlantsView", plants);
        }



        [HttpGet("api/price")]
        public ActionResult GetPrice()
        {

            var result = context.PlantConsumptions.Select(c => c.Price).Distinct().OrderBy(w => w);

            if (result is null)
            {
                return NotFound();
            }

            string json = JsonConvert.SerializeObject(result);
            return Ok(json);
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Diagnostics;
using TEST_TPLUS.Domains;
using TEST_TPLUS.Models;

namespace TEST_TPLUS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

		private readonly DataManager dataManager; 

		public HomeController(ILogger<HomeController> logger, DataManager dataManager)
        {
            _logger = logger;
			this.dataManager = dataManager;
		}

        public IActionResult Index()
        {
            return View();
        }

		public IActionResult Privacy()
        {
            return View();
        }

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HouseController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using TEST_TPLUS.Domain.Entities;
using TEST_TPLUS.Domains;
using static System.Net.WebRequestMethods;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Microsoft.DotNet.MSIdentity.Shared;
using System.Xml.Linq;
using static TEST_TPLUS.Controllers.HouseController;
using Microsoft.EntityFrameworkCore;
using System.Drawing;
using System.Collections.Generic;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Routing;
using TEST_TPLUS.Models;
using System.Diagnostics;

namespace TEST_TPLUS.Controllers
{
    public class HouseController : Controller
    {
        private readonly DataManager dataManager; // Для того, чтобы иметь доступ к базе данных

        public HouseController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        // GET: HouseController
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadFile(IFormFile jsonFile)
        {
            if (jsonFile != null && jsonFile.Length > 0)
            {   // Обработка файла
                using (var reader = new StreamReader(jsonFile.OpenReadStream()))
                {
                    var jsonString = reader.ReadToEnd();
                    var jsonObject = JObject.Parse(jsonString);

                    var map = new MappingProfile(); // Класс, для маппинга объектов пришедших с JSON

                    HRoot? houser = JsonConvert.DeserializeObject<HRoot>(jsonString);     
                    
                    // Сейвим в БД все, что связано с домами
                    foreach (var item in map.GetHouse(houser.Houses))
                    {
                        dataManager.Houses.SaveHouse(item);
                    }

                    PRoot? plantser = JsonConvert.DeserializeObject<PRoot>(jsonString);

                    // Сейвим в БД все, что связано с заводами
                    foreach (var item in map.GetPlant(plantser.Plants))
                    {
                        dataManager.Plants.SavePlant(item);
                    }
                   
                    return Ok("Файл успешно обработан \n" + jsonObject);
                }
            }
            else
            {
                ModelState.AddModelError("jsonFile", "Выберите файл JSON для загрузки");
                return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }
        }

        public IActionResult DownloadFile()
        {
            // Путь к файлу
            string file_path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Files/test.json");
            // Тип файла - content-type
            string file_type = "text/plain";
            // Имя файла - необязательно
            string file_name = "test.json";
            return PhysicalFile(file_path, file_type, file_name);
        }
    }
}

Views/Graph/HouseView.cshtml
@model List<Houses>
@{
    ViewData["Title"] = "График домов";
}


<div class="text-center">
    <h4 class="display-4">График потребления домов</h4>
    <div class="card">
        <div class="card-header">
            <div class="chart1">
                <canvas id="myChart2"></canvas>
            </div>
        </div>
    </div>
</div>



<script>

var Houses = [];    // Дома

    var Weather = [];   // Погода        

    var Colors = ['#ff0000', '#660066', '#00b300', '#3333cc'];

    var dataset = [];


    @if (Model.ToList().Count > 0)
    {
        int j = 0;
        foreach (var item in Model)
        {
            @:var Cons = []; // потребление

            for (int i = 0; i < item.Consumption.Count; i++)
            {               
                @:Cons.push(@Convert.ToInt32(item.Consumption[i])); 
            }

            @:dataset.push({label: "@Html.Raw(HttpUtility.JavaScriptStringEncode(item.Name.ToString()))", backgroundColor: 'transparent', borderColor: Colors[@j], borderWidth: 2, pointBorderColor: false,startAngle: 0, data: Cons, fill: false, lineTension: .4, showLine: true});
            j++;
        }
    }

        fetch('https://localhost:7296/api/weather')
        .then(response => response.json()).then(data => {
        data.forEach(weather => {
            Weather.push(weather)     
              })

        var Chart2 = document.getElementById('myChart2').getContext('2d');
        var chart = new Chart(Chart2, {
            type: 'line',
            data: {
               labels: Weather,
               datasets: dataset               
            },
            // Configuration options
            options: {
                title: {
                    display: true,
                    text: "График потребления домов"
                }
            }
        });
      })

</script>

Views/Graph/Index.cshtml
@*model IQueryable<House>*@
@model List<Houses>
@{
    ViewData["Title"] = "График";
}


<div class="text-center">
    <h4 class="display-4">График потребления домов</h4>
    <div class="card">
        <div class="card-header">
            <div class="chart1">
                <canvas id="myChart2"></canvas>
            </div>
        </div>
    </div>
</div>



<div class="text-center">
    <h4 class="display-4">График потребления заводов</h4>
    <div class="card">
        <div class="card-header">
            <div class="chart1">
                <canvas id="myChart3"></canvas>
            </div>
        </div>
    </div>
    <h3><a href="~/Home/Index">Back</a></h3>
</div>

<script>
    
    var Houses = [];    // Дома
    
    var Weather = [];   // Погода        

    var Colors = ['#ff0000', '#660066', '#00b300', '#3333cc'];

    var dataset = [];
       

    @if (Model.ToList().Count > 0)
    {
        int j = 0;
        foreach (var item in Model)
        {
            @:var Cons = []; // потребление

            for (int i = 0; i < item.Consumption.Count; i++)
            {               
                @:Cons.push(@Convert.ToInt32(item.Consumption[i])); 
            }

            @:dataset.push({label: "@Html.Raw(HttpUtility.JavaScriptStringEncode(item.Name.ToString()))", backgroundColor: 'transparent', borderColor: Colors[@j], borderWidth: 2, pointBorderColor: false,startAngle: 0, data: Cons, fill: false, lineTension: .4, showLine: true});
            j++;
        }
    }
        var arr = (Array.from(new Set(Weather))) // Группируем погоду
        
        fetch('https://localhost:7296/api/weather')
        .then(response => response.json()).then(data => {
        data.forEach(weather => {
            Weather.push(weather)  
            //console.log(weather)    
              })
        
        var Chart2 = document.getElementById('myChart2').getContext('2d');
        var chart = new Chart(Chart2, {
            type: 'line',
            data: {
               labels: Weather,
               datasets: dataset               
            },
            // Configuration options
            options: {
                title: {
                    display: true,
                    text: "График потребления домов"
                }
            }
        });
      })


              fetch('https://localhost:7296/api/weather')
        .then(response => response.json()).then(data => {
        data.forEach(weather => {
            console.log(weather)    
              })
         })

       var Chart3 = document.getElementById('myChart3').getContext('2d');
        var chart = new Chart(Chart3, {
            type: 'line',
            data: {
               labels: Weather,
               datasets: dataset               
            },
            // Configuration options
            options: {
                title: {
                    display: true,
                    text: "График потребления заводов"
                }
            }
        });
              
</script>

Views/Graph/PlantsView.cshtml
@model List<Plants>
@{
    ViewData["Title"] = "График заводов";
}


<div class="text-center">
    <h4 class="display-4">График потребления заводов</h4>
    <div class="card">
        <div class="card-header">
            <div class="chart1">
                <canvas id="myChart2"></canvas>
            </div>
        </div>
    </div>
</div>



<script>


    var Plants = [];    // Дома

    var Price = [];   // Погода        

    var Colors = ['#ff0000', '#660066', '#00b300', '#3333cc'];

    var dataset = [];


    @if (Model.ToList().Count > 0)
    {
        int j = 0;
        foreach (var item in Model)
        {
            @:var Cons = []; // потребление

            for (int i = 0; i < item.Consumption.Count; i++)
            {               
                @:Cons.push(@Convert.ToInt32(item.Consumption[i])); 
            }

            @:dataset.push({label: "@Html.Raw(HttpUtility.JavaScriptStringEncode(item.Name.ToString()))", backgroundColor: 'transparent', borderColor: Colors[@j], borderWidth: 2, pointBorderColor: false,startAngle: 0, data: Cons, fill: false, lineTension: .4, showLine: true});
            j++;
        }
    }

        fetch('https://localhost:7296/api/price')
        .then(response => response.json()).then(data => {
        data.forEach(price => {
            Price.push(price)  
            })

        var Chart2 = document.getElementById('myChart2').getContext('2d');
        var chart = new Chart(Chart2, {
            type: 'line',
            data: {
               labels: Price,
               datasets: dataset               
            },
            // Configuration options
            options: {
                title: {
                    display: true,
                    text: "График потребления заводов"
                }
            }
        });
      })

</script>

Views/Home/Index.cshtml
<!-- Intro -->
<section id="top" class="one dark cover">
    <div class="container">

        <header>
            <h2 class="alt">Hi! I'm <strong>Prologue</strong>, a <a href="http://html5up.net/license">free</a> responsive<br />
                site template designed by <a href="http://html5up.net">HTML5 UP</a>.</h2>
            <p>Ligula scelerisque justo sem accumsan diam quis<br />
                vitae natoque dictum sollicitudin elementum.</p>
        </header>

        <footer>
            <a href="#portfolio" class="button scrolly">Magna Aliquam</a>
        </footer>

    </div>
</section>

<!-- Portfolio -->


<!-- About Me -->
<section id="about" class="three">
    <div class="container">

        <header>
            <h2>About Me</h2>
        </header>

        <p>Tincidunt eu elit diam magnis pretium accumsan etiam id urna. Ridiculus
            ultricies curae quis et rhoncus velit. Lobortis elementum aliquet nec vitae
            laoreet eget cubilia quam non etiam odio tincidunt montes. Elementum sem
            parturient nulla quam placerat viverra mauris non cum elit tempus ullamcorper
            dolor. Libero rutrum ut lacinia donec curae mus vel quisque sociis nec
            ornare iaculis.</p>

    </div>
</section>

<!-- Contact -->
<section id="contact" class="four">
    <div class="container">

        <header>
            <h2>Contact</h2>
        </header>

        <p>Elementum sem parturient nulla quam placerat viverra
            mauris non cum elit tempus ullamcorper dolor. Libero rutrum ut lacinia
            donec curae mus. Eleifend id porttitor ac ultricies lobortis sem nunc
            orci ridiculus faucibus a consectetur. Porttitor curae mauris urna mi dolor.</p>

        <form method="post" action="#">
            <div class="row">
                <div class="col-6 col-12-mobile"><input type="text" name="name" placeholder="Name" /></div>
                <div class="col-6 col-12-mobile"><input type="text" name="email" placeholder="Email" /></div>
                <div class="col-12">
                    <textarea name="message" placeholder="Message"></textarea>
                </div>
                <div class="col-12">
                    <input type="submit" value="Send Message" />
                </div>
            </div>
        </form>

    </div>
</section>

@*<div>
    <h1>
        Главная страница
    </h1>
</div>
*@

Views/House/Index.cshtml
@model HouseViewModel
@{
    <section id="portfolio" class="two">
        <div class="container">
            <header>
                <h2>Добавить JSON</h2>
            </header>
        </div>

        <div>
            <label for="jsonFile">Выберите файл JSON:</label>
            <div class="div-box">
                @using (Html.BeginForm("UploadFile", "House", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div>
                        <input type="file" name="jsonFile" id="jsonFile" accept=".json" />
                    </div>
                    <div>
                        <input type="submit" value="Отправить" />
                    </div>
                }
            </div>
        </div>
    </section>
}

Views/Shared/CssPartial.cshtml
@*  Данный файл для подключения всей стилей CSS *@
@{
    <link rel="stylesheet" href="~/css/main.css" asp-asp-append-version="true"/>
}

Views/Shared/FooterPartial.cshtml
<!-- Copyright -->
<ul class="copyright">
    <li>&copy; Untitled. All rights reserved.</li>
    <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
</ul>

Views/Shared/HeaderPartial.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<div class="top">
    <!-- Logo -->
    <div id="logo">
        <span class="image avatar48"><img src="images/avatar.jpg" alt="" /></span>
        <h1 id="title">Jane Doe</h1>
        <p>Software Engineer</p>
    </div>

    <!-- Nav -->
    <nav id="nav">
        <ul>
            <li>
                <a asp-area="" asp-controller="House" asp-action="Index" asp-route-id=""><span class="icon solid fa-home">Добавить JSON</span></a>
            </li>
            <li>
                <a asp-area="" asp-controller="Graph" asp-action="GetHouses" asp-route-id=""><span class="icon solid fa-th">График потребления домов</span></a>
            </li>
            <li>
                <a asp-area="" asp-controller="Graph" asp-action="GetPlants" asp-route-id=""><span class="icon solid fa-th">График потребления заводов</span></a>
            </li>
        </ul>
    </nav>
</div>

Views/Shared/MainPartial.cshtml
<!-- Intro -->
<section id="top" class="one dark cover">
    <div class="container">
        <header>
            <h2 class="alt">
                Hi! I'm <strong>Prologue</strong>, a <a href="http://html5up.net/license">free</a> responsive<br />
                site template designed by <a href="http://html5up.net">HTML5 UP</a>.
            </h2>
            <p>
                Ligula scelerisque justo sem accumsan diam quis<br />
                vitae natoque dictum sollicitudin elementum.
            </p>
        </header>

        <footer>
            <a href="#portfolio" class="button scrolly">Magna Aliquam</a>
        </footer>
    </div>
</section>

<!-- Portfolio -->
<section id="portfolio" class="two">
    <div class="container">
        <header>
            <h2>Portfolio</h2>
        </header>

        <p>
            Vitae natoque dictum etiam semper magnis enim feugiat convallis convallis egestas rhoncus ridiculus in quis risus amet curabitur tempor orci penatibus. Tellus erat mauris ipsum fermentum etiam vivamus eget. Nunc nibh morbi quis
            fusce hendrerit lacus ridiculus.
        </p>

        <div class="row">
            <div class="col-4 col-12-mobile">
                <article class="item">
                    <a href="#" class="image fit"><img src="images/pic02.jpg" alt="" /></a>
                    <header>
                        <h3>Ipsum Feugiat</h3>
                    </header>
                </article>
                <article class="item">
                    <a href="#" class="image fit"><img src="images/pic03.jpg" alt="" /></a>
                    <header>
                        <h3>Rhoncus Semper</h3>
                    </header>
                </article>
            </div>
            <div class="col-4 col-12-mobile">
                <article class="item">
                    <a href="#" class="image fit"><img src="images/pic04.jpg" alt="" /></a>
                    <header>
                        <h3>Magna Nullam</h3>
                    </header>
                </article>
                <article class="item">
                    <a href="#" class="image fit"><img src="images/pic05.jpg" alt="" /></a>
                    <header>
                        <h3>Natoque Vitae</h3>
                    </header>
                </article>
            </div>
            <div class="col-4 col-12-mobile">
                <article class="item">
                    <a href="#" class="image fit"><img src="images/pic06.jpg" alt="" /></a>
                    <header>
                        <h3>Dolor Penatibus</h3>
                    </header>
                </article>
                <article class="item">
                    <a href="#" class="image fit"><img src="images/pic07.jpg" alt="" /></a>
                    <header>
                        <h3>Orci Convallis</h3>
                    </header>
                </article>
            </div>
        </div>
    </div>
</section>

<!-- About Me -->
<section id="about" class="three">
    <div class="container">
        <header>
            <h2>About Me</h2>
        </header>

        <a href="#" class="image featured"><img src="images/pic08.jpg" alt="" /></a>

        <p>
            Tincidunt eu elit diam magnis pretium accumsan etiam id urna. Ridiculus ultricies curae quis et rhoncus velit. Lobortis elementum aliquet nec vitae laoreet eget cubilia quam non etiam odio tincidunt montes. Elementum sem
            parturient nulla quam placerat viverra mauris non cum elit tempus ullamcorper dolor. Libero rutrum ut lacinia donec curae mus vel quisque sociis nec ornare iaculis.
        </p>
    </div>
</section>

Views/Shared/MetaTagsPartial.cshtml
@using TEST_TPLUS.Service;
@* Храним метатеги + Тайатл *@
@{
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	@*Ставим динамичское название сайта, название подтягивается с БД*@
	@if (ViewBag.Title != null)
	{
		<title>@ViewBag.Title</title>
	}
	else
	{
		<title>@Config.CompanyName</title>	
	}
	@if (ViewBag.Description != null) // Подтягиваем описание сайта  cБД
	{
		<meta name="description" content=" @ViewBag.Description" />
	}
	@if (ViewBag.Keywords != null)  // Ключевые слова
	{
		<meta name="keywords" content=" @ViewBag.Keywords" />
	}
}

Views/Shared/ScriptsPartial.cshtml
<!-- Scripts -->
@*<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/jquery.scrolly.min.js"></script>
<script src="assets/js/jquery.scrollex.min.js"></script>
<script src="assets/js/browser.min.js"></script>
<script src="assets/js/breakpoints.min.js"></script>
<script src="assets/js/util.js"></script>
<script src="assets/js/main.js"></script>*@
@*Не используем эти скрипты, а подтянем их всего один раз в целях оптимизации (asp-append-version="true") c помощью bundler упакуем все.*@
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	@await Html.PartialAsync("MetaTagsPartial") @*// Подключаем метатеги*@
	@await Html.PartialAsync("CssPartial")	    @*// Подключаем CSS*@
</head>
<body class="is-preload">
	<div id="header">
		@await Html.PartialAsync("HeaderPartial")	    @*// Подключаем Header*@
	</div>
	<div id="main">
		@RenderBody()
	</div>
	<div id="footer">
	<!-- Footer -->
		@await Html.PartialAsync("FooterPartial")	    @*// Подключаем Footer*@
	</div>
	<!-- Scripts -->
	@await Html.PartialAsync("ScriptsPartial")	    @*// Подключаем JS скрипты*@
</body>
</html>